CREATE TABLE "CATEGORY"(
"ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
"NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE "RECIPE"(
"ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
"NAME" VARCHAR(255) NOT NULL,
"PROCEDURE" TEXT NOT NULL,
"DATE" DATE
);

CREATE TABLE "RC_DEPENDENCY"(
"RECIPE_ID" BIGINT REFERENCES RECIPE (ID),
"CATEGORY_ID" BIGINT REFERENCES CATEGORY (ID)
);

CREATE TABLE "INGREDIENTS"(
"RECIPE_ID" BIGINT REFERENCES RECIPE (ID),
"NAME" VARCHAR(255) NOT NULL
);

